### ISSUE TITLE
how to install a specific version

### ISSUE THREAD

**Issue by or2008** [paritytech/homebrew-paritytech#60]
is there a way to install a specific parity version via homebrew 

for example something like:

brew install parity@1.7.2

**Comment by 5chdn** [comment]
https://stackoverflow.com/a/4158763/1260906

**Comment by chmanie** [comment]
I'm sorry but this isn't really helpful.

Option 1) and 2) obviously don't work when you haven't installed the desired version before.

Option 3) pretty much relies on `brew versions` which isn't available anymore and also shouldn't be used. Nevertheless when I do `brew tap homebrew/boneyard`, `brew versions` still is not a valid command. Furthermore the `/usr/local/homebrew/Library/Formula` directory doesn't exist anymore. I'm not saying this is anyone's fault here, just that the linked solution doesn't work.

Has anyone successfully managed to do that with a current version of homebrew?

**Comment by chmanie** [comment]
OK here we go:

0) You should have done `brew tap paritytech/paritytech` and `brew update`

1) Find the commit hash that specifies the correct version here:

https://github.com/paritytech/homebrew-paritytech/commits/master/parity.rb

Also note whether it is in the stable or latest section.

*Note*: find the newest one that still specifies the same version, otherwise the `sha256` won't match. 

2) Do
```
brew install https://raw.githubusercontent.com/paritytech/homebrew-paritytech/{COMMIT_HASH}/parity.rb [--stable]
```

Use the `--stable` flat if you noted that before.
