### ISSUE TITLE
Support for LinuxBrew

### ISSUE THREAD

**Issue by unixfox** [paritytech/homebrew-paritytech#69]
[Linuxbrew](http://linuxbrew.sh/) is a port of homebrew for Linux.
Currently parity on homebrew download the binary for Apple. Is it possible to add a support for Linuxbrew by providing Linux binary if the host is Linux?

**Comment by 5chdn** [comment]
This is out of scope. If you want to contribute for Linuxbrew, we appreciate pull-requests.

Otherwise, we do not plan to support it yet. We already have Snapcraft support and packages for Debian, Ubuntu, Centos, as well as binaries for manual installation. In addition, it's available in the official ArchLinux repositories.

https://snapcraft.io/parity

https://vanity-service.parity.io/parity-binaries?format=markdown&version=beta-release

https://www.archlinux.org/packages/community/x86_64/parity/
